#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "WindSmiths01"
  https://create.arduino.cc/cloud/things/d4f50224-c273-4f2a-8b98-1ea643195c34 

  Arduino IoT Cloud Properties description

  The following variables are automatically generated and updated when changes are made to the Thing properties

  float temperature;
  bool button;
  bool tilt;

  Properties which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "Averager.h"

int TILT_PIN = 0;
int BUTTON_PIN = 1;
int LED_PIN = 2;
int TEMP_PWR_PIN = 3;
int TEMP_PIN = A6;

Averager averageTemperature;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(TILT_PIN, INPUT_PULLUP);
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(LED_PIN, OUTPUT);
  pinMode(TEMP_PWR_PIN, OUTPUT);
  
  digitalWrite(TEMP_PWR_PIN, 1);
}


float getTemperatureDegC() {
  return (map(analogRead(TEMP_PIN), 0, 1023, 0, 3300)-500)/10.0;
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  tilt = digitalRead(TILT_PIN);
  button = digitalRead(BUTTON_PIN);
  float temperatureReading = getTemperatureDegC();
  averageTemperature.addReading(temperatureReading);
  temperature = averageTemperature.getAverage();
  digitalWrite(LED_BUILTIN, tilt);
  digitalWrite(LED_PIN, button);
  Serial.println(temperature);
  delay(1000);
  
}
